Tidy markdown
chef/chef-apply pull request #191
Opened 2021-08-24 10:25 UTC by damacus

Add yamllint check
Add chefstyle check
Add markdown check
Add spellcheck from chef/chef

Signed-off-by: Dan Webb <dan.webb@damacus.io>

2021-08-24 15:35 UTC, tas50 commented on cspell.json
> +    "ABORTIFHUNG",
Where did this list come from?

2021-08-31 09:53 UTC, damacus commented on .github/workflows/lint.yaml
> +name: lint
I kind of understand this POV, but don't we have lint checks in other places. And from my perspective, hopefully it increases the quality of the markdown in the repo. There are just too many people who don't understand how to write markdown properly, so this at least gives them a helping hand.

2021-08-31 16:59 UTC, vkarve-chef approved these changes

2021-08-31 23:50 UTC, tas50 requested changes
I can live with markdown enforcement and yaml enforcement as long as it doesn't impact potential contributions. This does need some cleanup to the cspell config though. Remove all the exceptions and see specifically what we need. Things that are generic computing terms should go in https://github.com/chef/chef_dictionary/ and things that are very specific to this project should go back into the config directly.

2021-09-01 09:42 UTC, damacus commented
> I can live with markdown enforcement and yaml enforcement as long as it doesn't impact potential contributions. 

Thankfully we're not requiring yaml or makrdown lint to pass here, so we can merge with errors 👍🏼

2022-01-04 18:17 UTC, nikhil2611 approved these changes

2022-01-04 18:28 UTC, merged